apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-operator-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: overlays/loki-operator/dev
    repoURL: https://github.com/lmtbelmonte/lmt-argo-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
