---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  name: openshift-gitops-operator
  namespace: openshift-gitops-operator
spec:
  channel: gitops-1.12
  installPlanApproval: Automatic
  name: openshift-gitops-operator
  source: redhat-operators-index
  sourceNamespace: openshift-marketplace
  config:
    env:
      - name: ARGOCD_CLUSTER_CONFIG_NAMESPACES
        value: infra-gitops
      - name: DISABLE_DEFAULT_ARGOCD_INSTANCE
        value: "true"
    nodeSelector:
      node-role.kubernetes.io/infra: ""
    tolerations:
      - effect: NoExecute
        key: node-role.kubernetes.io/infra
        value: reserved
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        value: reserved
