#plaapiVersion: operators.coreos.com/v1
#kind: OperatorGroup
#metadata:
# name: cluster-observability-operator
# namespace: openshift-logging
#spec:
#  targetNamespaces:
#  - openshift-logging
#---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cluster-observability-operator
  namespace: openshift-logging
spec:
  channel: development
  name: cluster-observability-operator
  installPlanApproval: Automatic
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: cluster-observability-operator.0.4.1
