#apiVersion: operators.coreos.com/v1
#kind: OperatorGroup
#metadata:
 # name: observability-operator-group
#  namespace: openshift-logging
#spec:
#  targetNamespaces:
#  - openshift-logging
#---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cluster-observability
  namespace: openshift-logging
spec:
  channel: stable
  name: cluster-observability
  installPlanApproval: Automatic
  source: redhat-operators
  sourceNamespace: openshift-marketplace
