apiVersion: observability.openshift.io/v1alpha1
kind: UIPlugin
metadata:
  name: logging
  labels:
    app.kubernetes.io/instance: cluster-observability-app
spec:
  logging:
    lokiStack:
      name: logging-loki
  type: Logging
