apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: observability-plugin
  namespace: openshift-logging
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: uiplugins.observability.openshift.io-v1alpha1-admin
  apiGroup: "" 
