apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: observability-ui-plugin-rolebinding
  namespace: openshift-logging
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    apiGroup: observability.openshift.io
roleRef:
  kind: ClusterRole
  name: uiplugins.observability.openshift.io-v1alpha1-admin
  apiGroup: rbac.authorization.k8s.io 
