apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: loki-argo
  namespace: openshift-logging
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  kind: ClusterRole
  name: uiplugins.observability.openshift.io-v1alpha1-admin
  apiGroup: rbac.authorization.k8s.io 
