apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - logging-log-forwarder.yaml
  - logging-clusterRole-binding.yaml
 # - logging-loki-ingester-reclaimjob-0.yaml
 # - logging-loki-ingester-reclaimjob-1.yaml
  - logging-enable-console-plugin.yaml
  - logging-uiplugin.yaml
  - lfme-instance.yaml
  