apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  name: devspaces
  namespace: openshift-devspaces
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "3"
spec:
  components:
    cheServer:
      debug: false
      logLevel: INFO
    dashboard:
      logLevel: ERROR
    devWorkspace: {}
    devfileRegistry:
      externalDevfileRegistries:
        - url: "https://github.com/devfile-samples/devfile-sample-java-springboot-basic/blob/main/devfile.yaml" 
    imagePuller:
      enable: false
      spec: {}
    metrics:
      enable: true
    pluginRegistry:
      openVSXURL: 'https://open-vsx.org'
  containerRegistry: {}
  devEnvironments:
    startTimeoutSeconds: 300
    security: {}
    secondsOfRunBeforeIdling: -1
    maxNumberOfWorkspacesPerUser: -1
    containerBuildConfiguration:
      openShiftSecurityContextConstraint: container-build
    ignoredUnrecoverableEvents:
      - FailedScheduling
    maxNumberOfRunningWorkspacesPerUser: 3
    deploymentStrategy: RollingUpdate
    defaultNamespace:
      autoProvision: true
      template: <username>-devspaces
    secondsOfInactivityBeforeIdling: 7200
    storage:
      perUserStrategyPvcConfig:
        claimSize: 10Gi
 #      storageClass: managed-csi-encrypted-cmk
        storageClass: managed-csi
      perWorkspaceStrategyPvcConfig:
        claimSize: 10Gi
 #      storageClass: managed-csi-hdd
        storageClass: managed-csi
      pvcStrategy: per-workspace
 #  tolerations:
 #    - effect: NoSchedule
 #      key: node-role.kubernetes.io/workerdev
 #      operator: Exists
    persistUserHome:
      enabled: true
  gitServices: {}
  networking:
    auth:
      gateway:
        configLabels:
          app: che
          component: che-gateway-config
        kubeRbacProxy:
          logLevel: 0
        oAuthProxy:
          cookieExpireSeconds: 86400
        traefik:
          logLevel: INFO
